<section class="players">

<?php foreach($data["players"] as $player): ?>

<div class="player-card">

<h3><?= $player->getNickname(); ?></h3>

<img src="<?= $player->getPortrait()->getUrl(); ?>" 
     alt="<?= $player->getPortrait()->getAlt(); ?>">

</div>

<?php endforeach; ?>

</section>


<section class="last-teams">

<?php foreach ($data["teams"] as $team): ?>

<div class="team">

<img src="<?= $team->getLogo()->getUrl(); ?>"
     alt="<?= $team->getLogo()->getAlt(); ?>">

<h3><?= $team->getName(); ?></h3>

</div>

<?php endforeach; ?>

</section>