<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8" />
        <title>mini Projet MVC</title>
        <link rel="stylesheet" href="assets/style.css" />
    </head>
    <body>
            <header>
            <nav>
             <ul>
               <a href="index.php">Home</a>
               <a href="index.php?route=teams">Les Teams</a>
                <a href="index.php?route=players">Les players</a>
              <a href="index.php?route=matchs">Les Match</a>
        </ul>
            </nav>
        </header>
        <?php
             require  "templates/$template.phtml";
        ?>
    </body>
</html>